stages:
  - build

build:
  stage: build
  tags: 
    - production
  script:
    - gem build -o remistify.gem remistify.gemspec
    - rake test
  artifacts:
    paths:
    - remistify.gem
    expire_in: 1 year
